import urllib.request
class Pokemon ():

    def __init__ (self, pokemon_name, pokemon_indexnr, pokemon_sprite, pokemon_picture, pokemon_type, pokemon_type2, pokemon_versionen = None):
        self.pokemon_name = pokemon_name
        self.pokemon_indexnr = pokemon_indexnr
        self.pokemon_sprite = pokemon_sprite
        self.pokemon_picture = pokemon_picture
        self.pokemon_type = pokemon_type
        self.pokemon_type2 = pokemon_type2
        self.pokemon_versionen = pokemon_versionen

    def get_name(self):
        return self.pokemon_name

    def get_indexnr(self):
        return self.pokemon_indexnr

    def get_sprite(self):
        return self.pokemon_sprite

    def get_picture(self):
        return self.pokemon_picture

    def get_type(self):
        if self.pokemon_type2 == None:
            return self.pokemon_type
        else:
            return str(self.pokemon_type, self.pokemon_type2)

    def get_versionen(self):
        return self.pokemon_versionen

#Links to the folders
#https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/tree/main/Uranium/Pokemon
#https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/tree/main/Uranium/Mega
#https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/tree/main/Uranium/Nuclear
#https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/tree/main/Uranium/Sprites

#Links to the pictures
#https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/001Popkas.png
#https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/002_1Popkas.png
#https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N007Popkas.png
#https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon001.gif

#001-#010
Orchynx = Pokemon("Orchynx", "#001", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon001.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/001Popkas.png", "Grass", "Steel")
Mega_Metalynx = Pokemon("Mega Metalynx", "#002", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon002.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/002_1Popkas.png", "Grass", "Steel")
Metalynx = Pokemon("Metalynx", "#002", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon002.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/002Popkas.png", "Grass", "Steel", Mega_Metalynx)
Raptorch = Pokemon("Raptorch", "#003", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon003.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/003Popkas.png", "Fire", "Ground")
Mega_Archilles = Pokemon("Mega Archilles", "#004", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon004.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/004_1Popkas.png", "Fire", "Ground")
Archilles = Pokemon("Archilles", "#004", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon004.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/004Popkas.png", "Fire", "Ground", Mega_Archilles)
Eletux = Pokemon("Eletux", "#005", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon005.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/005Popkas.png", "Water", "Electric")
Mega_Electruxo = Pokemon("Mega Electruxo", "#006", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon006.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/006_1Popkas.png", "Water", "Electric")
Electruxo = Pokemon("Electruxo", "#006", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon006.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/006Popkas.png", "Water", "Electric", Mega_Electruxo)
Nuclear_Chyinmunk = Pokemon("Nuclear Chyinmunk", "#007", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon007.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N007Popkas.png", "Normal", "Nuclear")
Chyinmunk = Pokemon("Chyinmunk", "#007", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon007.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/007Popkas.png", "Normal", None, Nuclear_Chyinmunk)
Nuclear_Kinetmunk = Pokemon("Kinetmunk", "#008", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon008.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N008Popkas.png", "Normal", "Nuclear")
Kinetmunk = Pokemon("Kinetmunk", "#008", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon008.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/008Popkas.png", "Normal", "Electric", Nuclear_Kinetmunk)
Birbie = Pokemon("Birbie", "#009", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon009.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/009Popkas.png", "Normal", "Flying")
Aveden = Pokemon("Aveden", "#010", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon010.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/010Popkas.png", "Normal", "Flying")
#011-#020
Splendifowl = Pokemon("Splendifowl", "#011", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon011.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/011Popkas.png", "Normal", "Flying")
Cubbug = Pokemon("Cubbug", "#012", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon012.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/012Popkas.png", "Bug", None)
Cubblfly = Pokemon("Cubblfly", "#013", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon013.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/013Popkas.png", "Bug", "Fairy")
Nimflora = Pokemon("Nimflora", "#014", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon014.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/014Popkas.png", "Bug", "Fairy")
Barewl = Pokemon("Barewl", "#015", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon015.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/015Popkas.png", "Steel", "Rock")
Dearewl = Pokemon("Dearewl", "#016", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon016.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/016Popkas.png", "Steel", "Rock")
Gararewl = Pokemon("Gararewl", "#017", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon017.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/017Popkas.png", "Steel", None)
Grozard = Pokemon("Grozard", "#018", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon018.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/018Popkas.png", "Ground", None)
Terlard = Pokemon("Terlard", "#019", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon019.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/019Popkas.png", "Ground", "Dragon")
Nuclear_Tonemy = Pokemon("Nuclear Tonemy", "#020", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon020.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N020Popkas.png", "Poison", None)
Tonemy = Pokemon("Tonemy", "#020", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon020.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/020Popkas.png", "Poison", None, Nuclear_Tonemy)
#021-#030
Nuclear_Tofurang = Pokemon("Nuclear Tofurang", "#021", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon021.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N021Popkas.png", "Poison", None)
Tofurang = Pokemon("Tofurang", "#021", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon021.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/021Popkas.png", "Poison", None, Nuclear_Tofurang)
Dunsparce = Pokemon("Dunsparce", "#022", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon022.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/022Popkas.png", "Normal", None)
Dunseraph = Pokemon("Dunseraph", "#023", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon023.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/023Popkas.png", "Dragon", "Flying")
Fortog = Pokemon("Fortog", "#024", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon024.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/024Popkas.png", "Water", "Poison")
Folerog = Pokemon("Folerog", "#025", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon025.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/025Popkas.png", "Water", "Poison")
Blubelrog = Pokemon("Blubelrog", "#026", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon026.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/026Popkas.png", "Water", "Poison")
Nuclear_Magikarp = Pokemon("Nuclear Magikarp", "#027", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon027.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N027Popkas.png", "Water", "Nuclear")
Magikarp = Pokemon("Magikarp", "#027", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon027.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/027Popkas.png", "Water", None, Nuclear_Magikarp)
Mega_Nuclear_Gyarados = Pokemon("Mega Nuclear Gyarados", "#028", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon028.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N028Popkas.png", "Water", "Nuclear")
Mega_Gyarados = Pokemon("Mega Gyarados", "#028", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon028.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/028_1Popkas.png", "Water", "Dark", Mega_Nuclear_Gyarados)
Gyarados = Pokemon("Gyarados", "#028", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon028.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/028Popkas.png", "Water", "Flying", Mega_Gyarados)
Feleng = Pokemon("Feleng", "#029", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon029.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/029Popkas.png", "Normal", None)
Felunge = Pokemon("Felunge", "#030", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon030.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/030Popkas.png", "Normal", None)
#031-#040
Feliger = Pokemon("Feliger", "#031", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon031.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/031Popkas.png", "Normal", None)
Mankey = Pokemon("Mankey", "#032", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon032.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/032Popkas.png", "Fighting", None)
Primeape = Pokemon("Primeape", "#033", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon033.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/033Popkas.png", "Fighting", None)
Empirilla = Pokemon("Empirilla", "#034", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon034.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/034Popkas.png", "Fighting", None)
Nuclear_Owten = Pokemon("Nuclear Owten", "#035", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon035.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N035Popkas.png", "Normal", "Nuclear")
Owten = Pokemon("Owten", "#035", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon035.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/035Popkas.png", "Normal", "Flying", Nuclear_Owten)
Nuclear_Eshouten = Pokemon("Nuclear Eshouten", "#036", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon036.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N036Popkas.png", "Normal", "Nuclear")
Eshouten = Pokemon("Eshouten", "#036", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon036.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/036Popkas.png", "Normal", "Flying", Nuclear_Eshouten)
Lotad = Pokemon("Lotad", "#037", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon037.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/037Popkas.png", "Water", "Grass")
Lombre = Pokemon("Lombre", "#038", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon038.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/038Popkas.png", "Water", "Grass")
Ludicolo = Pokemon("Ludicolo", "#039", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon039.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/039Popkas.png", "Water", "Grass")
Smore = Pokemon("Smore", "#040", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon040.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/040Popkas.png", "Bug", None)
#041-#050
Firoke = Pokemon("Firoke", "#041", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon041.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/041Popkas.png", "Bug", "Fire")
Brailip = Pokemon("Brailip", "#042", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon042.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/042Popkas.png", "Water", "Psychic")
Brainoar = Pokemon("Brainoar", "#043", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon043.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/043Popkas.png", "Water", "Psychic")
Nuclear_Ekans = Pokemon("Nuclear Ekans", "#044", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon044.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N044Popkas.png", "Poison", "Nuclear")
Ekans = Pokemon("Ekans", "#044", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon044.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/044Popkas.png", "Poison", None, Nuclear_Ekans)
Mega_Nuclear_Arbok = Pokemon("Mega Nuclear Arbok", "#045", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon045.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N045Popkas.png", "Poison", "Nuclear")
Mega_Arbok = Pokemon("Mega Arbok", "#045", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon045.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/045_1Popkas.png", "Poison", "Dark", Mega_Nuclear_Arbok)
Arbok = Pokemon("Arbok", "#045", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon045.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/045Popkas.png", "Poison", None, Mega_Arbok)
Nuclear_Tancoon = Pokemon("Nuclear Tancoon", "#046", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon046.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N046Popkas.png", "Dark", "Nuclear")
Tancoon = Pokemon("Tancoon", "#046", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon046.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/046Popkas.png", "Dark", "Normal", Nuclear_Tancoon)
Nuclear_Tanscure = Pokemon("Nuclear Tanscure", "#047", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon047.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N047Popkas.png", "Dark", "Nuclear")
Tanscure = Pokemon("Tanscure", "#047", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon047.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/047Popkas.png", "Dark", "Normal", Nuclear_Tanscure)
Sponee = Pokemon("Sponee", "#048", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon048.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/048Popkas.png", "Bug", None)
Sponaree = Pokemon("Sponaree", "#049", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon049.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/049Popkas.png", "Bug", "Water")
Nuclear_Pahar = Pokemon("Nuclear Pahar", "#050", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon050.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N050Popkas.png", "Fire", "Nuclear")
Pahar = Pokemon("Pahar", "#050", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon050.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/050Popkas.png", "Fire", "Flying", Nuclear_Pahar)
#051-#060
Nuclear_Palij = Pokemon("Nuclear Palij", "#051", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon051.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N051Popkas.png", "Fire", "Nuclear")
Palij = Pokemon("Palij", "#051", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon051.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/051Popkas.png", "Fire", "Flying", Nuclear_Palij)
Nuclear_Pajay = Pokemon("Nuclear Pajay", "#052", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon052.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N052Popkas.png", "Fire", "Nuclear")
Pajay = Pokemon("Pajay", "#052", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon052.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/052Popkas.png", "Fire", "Flying", Nuclear_Pajay)
Nuclear_Jerbolta = Pokemon("Nuclear Jerbolta", "#053", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon053.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N052Popkas.png", "Electric", "Nuclear")
Jerbolta = Pokemon("Jerbolta", "#053", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon053.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/053Popkas.png", "Electric", "Ground", Nuclear_Jerbolta)
Comite = Pokemon("Comite", "#054", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon054.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/054Popkas.png", "Rock", None)
Cometeor = Pokemon("Cometeor", "#055", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon055.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/055Popkas.png", "Rock", "Psychic")
Astronite = Pokemon("Astronite", "#056", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon056.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/056Popkas.png", "Rock", "Psychic")
Mareep = Pokemon("Mareep", "#057", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon057.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/057Popkas.png", "Electric", None)
Flaaffy = Pokemon("Flaaffy", "#058", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon058.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/058Popkas.png", "Electric", None)
Mega_Amphoros = Pokemon("Mega Ampharos", "#059", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon059.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/059_1Popkas.png", "Electric", "Dragon")
Ampharos = Pokemon("Ampharos", "#059", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon059.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/059Popkas.png", "Electric", None, Mega_Amphoros)
Nuclear_Baashaun = Pokemon("Nuclear Baashaun", "#060", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon060.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N060Popkas.png", "Dark", "Nuclear")
Baashaun = Pokemon("Baashaun", "#060", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon060.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/060Popkas.png", "Dark", "Fighting", Nuclear_Baashaun)
#061-#070
Nuclear_Baaschaf = Pokemon("Nuclear Baaschaf", "#061", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon061.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N061Popkas.png", "Dark", "Nuclear")
Baaschaf = Pokemon("Baaschaf", "#061", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon061.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/061Popkas.png", "Dark", "Fighting", Nuclear_Baaschaf)
Mega_Nuclear_Baariette = Pokemon("Mega Nuclear Baariette", "#062", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon062.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N062Popkas.png", "Dark", "Nuclear")
Mega_Baariette = Pokemon("Mega Baariette", "#062", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon062.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/062_1Popkas.png", "Dark", "Fighting", Mega_Nuclear_Baariette)
Baariette = Pokemon("Baariette", "#062", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon062.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/062Popkas.png", "Dark", "Fighting", Mega_Baariette)
Tricwe = Pokemon("Tricwe", "#063", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon063.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/063Popkas.png", "Bug", None)
Harylect = Pokemon("Harylect", "#064", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon064.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/064Popkas.png", "Bug", "Electric")
Nuclear_Costraw = Pokemon("Nuclear Costraw", "#065", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon065.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N065Popkas.png", "Poison", "Nuclear")
Costraw = Pokemon("Costraw", "#065", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon065.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/065Popkas.png", "Poison", "Psychic", Nuclear_Costraw)
Nuclear_Trawpint = Pokemon("Trawpint", "#066", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon066.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N066Popkas.png", "Poison", "Nuclear")
Trawpint = Pokemon("Trawpint", "#066", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon066.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/066Popkas.png", "Poison", "Psychic", Nuclear_Trawpint)
Lunapup = Pokemon("Lunapup", "#067", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon067.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/067Popkas.png", "Ground", "Fighting")
Herolune = Pokemon("Herolune", "#068", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon068.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/068Popkas.png", "Ground", "Fighting")
Minyan = Pokemon("Minyan", "#069", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon069.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/069Popkas.png", "Dark", "Poison")
Vilucard = Pokemon("Vilucard", "#070", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon070.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/070Popkas.png", "Dark", "Poison")
#071-#080
Buizel = Pokemon("Buizel", "#071", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon071.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/071Popkas.png", "Water", None)
Floatzel = Pokemon("Floatzel", "#072", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon072.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/072Popkas.png", "Water", None)
Modrille = Pokemon("Modrille", "#073", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon073.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/073Popkas.png", "Ground", "Dark")
Mega_Drilgann = Pokemon("Mega Drilgann", "#074", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon074.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/074_1Popkas.png", "Ground", "Dark")
Drilgann = Pokemon("Drilgann", "#074", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon074.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/074Popkas.png", "Ground", "Dark", Mega_Drilgann)
Nuclear_Gligar = Pokemon("Nuclear Gligar", "#075", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon075.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N075Popkas.png", "Ground", "Nuclear")
Gligar = Pokemon("Gligar", "#075", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon075.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/075Popkas.png", "Ground", "Flying", Nuclear_Gligar)
Nuclear_Gliscor = Pokemon("Nuclear Gliscor", "#076", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon076.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N076Popkas.png", "Ground", "Nuclear")
Gliscor = Pokemon("Gliscor", "#076", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon076.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/076Popkas.png", "Ground", "Flying", Nuclear_Gliscor)
Mega_Sableye = Pokemon("Mega Sableye", "#077", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon077.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/077_1Popkas.png", "Dark", "Ghost")
Sableye = Pokemon("Sableye", "#077", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon077.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/077Popkas.png", "Dark", "Ghost", Mega_Sableye)
Cocaran = Pokemon("Cocaran", "#078", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon078.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/078Popkas.png", "Grass", "Ground")
Cararalm = Pokemon("Cararalm", "#079", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon079.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/079Popkas.png", "Grass", "Ground")
Cocancer = Pokemon("Cocancer", "#080", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon080.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/080Popkas.png", "Grass", "Ground")
#081-#090
Nuclear_Corsola = Pokemon("Nuclear Corsola", "#081", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon081.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N081Popkas.png", "Water", "Nuclear")
Corsola = Pokemon("Corsola", "#081", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon081.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/081Popkas.png", "Water", "Rock", Nuclear_Corsola)
Nuclear_Corsoreef = Pokemon("Nuclear Corsoreef", "#082", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon082.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N082Popkas.png", "Water", "Nuclear")
Corsoreef = Pokemon("Corsoreef", "#082", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon082.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/082Popkas.png", "Water", "Rock", Nuclear_Corsoreef)
Nuclear_Tubjaw = Pokemon("Nuclear Tubjaw", "#083", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon083.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N083Popkas.png", "Water", "Nuclear")
Tubjaw = Pokemon("Tubjaw", "#083", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon083.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/083Popkas.png", "Water", "Dark", Nuclear_Tubjaw)
Nuclear_Tubareel = Pokemon("Nuclear Tubareel", "#084", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon084.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N084Popkas.png", "Water", "Nuclear")
Tubareel = Pokemon("Tubareel", "#084", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon084.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/084Popkas.png", "Water", "Dark", Nuclear_Tubareel)
Cassnail = Pokemon("Cassnail", "#085", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon085.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/085Popkas.png", "Ground", "Water")
Sableau = Pokemon("Sableau", "#086", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon086.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/086Popkas.png", "Ground", "Water")
Escartress = Pokemon("Escartress", "#087", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon087.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/087Popkas.png", "Ground", "Water")
Nuclear_Nupin = Pokemon("Nuclear Nupin", "#088", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon088.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N088Popkas.png", "Grass", "Nuclear")
Nupin = Pokemon("Nupin", "#088", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon088.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/088Popkas.png", "Grass", "Electric", Nuclear_Nupin)
Nuclear_Gellin = Pokemon("Nuclear Gellin", "#089", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon089.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N089Popkas.png", "Grass", "Nuclear")
Gellin = Pokemon("Gellin", "#089", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon089.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/089Popkas.png", "Grass", "Electric", Nuclear_Gellin)
Cottonee = Pokemon("Cottonee", "#090", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon090.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/090Popkas.png", "Grass", "Fairy")
#091-#100
Mega_Whimsicott = Pokemon("Mega Whimsicott", "#091", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon091.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/091_1Popkas.png", "Grass", "Fairy")
Whimsicott = Pokemon("Whimsicott", "#091", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon091.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/091Popkas.png", "Grass", "Fairy", Mega_Whimsicott)
Misdreavus = Pokemon("Misdreavus", "#092", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon092.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/092Popkas.png", "Ghost", None)
Mismagius = Pokemon("Mismagius", "#093", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon093.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/093Popkas.png", "Ghost", None)
Nuclear_Barand = Pokemon("Nuclear Barand", "#094", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon094.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N094Popkas.png", "Dragon", "Nuclear")
Barand = Pokemon("Barand", "#094", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon094.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/094Popkas.png", "Dragon", None, Nuclear_Barand)
Glaslug = Pokemon("Glaslug", "#095", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon095.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/095Popkas.png", "Water", "Ice")
Glavinug = Pokemon("Glavinug", "#096", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon096.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/096Popkas.png", "Water", "Ice")
S_fifty_one = Pokemon("S51", "#097", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon097.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/097Popkas.png", "Psychic", "Steel")
Mega_S_fity_one_A = Pokemon("Mega S51-A", "#098", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon098.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/098_1Popkas.png", "Psychic", "Steel")
S_fifty_one_A = Pokemon("S51-A", "#098", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon098.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/098Popkas.png", "Psychic", "Steel")
Nuclear_Paraudio = Pokemon("Nuclear Paraudio", "#099", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon099.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N099Popkas.png", "Normal", "Nuclear")
Paraudio = Pokemon("Paraudio", "#099", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon099.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/099Popkas.png", "Normal", "Psychic", Nuclear_Paraudio)
Nuclear_Paraboom = Pokemon("Nuclear Paraboom", "#100", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon100.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N100Popkas.png", "Normal", "Nuclear")
Paraboom = Pokemon("Paraboom", "#100", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon100.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/100Popkas.png", "Normal", "Psychic", Nuclear_Paraboom)
#101-#110
Flager = Pokemon("Flager", "#101", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon101.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/101Popkas.png", "Fire", None)
Mega_Inflagetah = Pokemon("Mega Inflagetah", "#102", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon102.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/102_1Popkas.png", "Fire", None)
Inflagetah = Pokemon("Inflagetah", "#102", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon102.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/102Popkas.png", "Fire", None, Mega_Inflagetah)
Chimical = Pokemon("Chimical", "#103", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon103.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/103Popkas.png", "Fire", "Poison")
Chimaconda = Pokemon("Chimaconda", "#104", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon104.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/104Popkas.png", "Fire", "Poison")
Tikiki = Pokemon("Tikiki", "#105", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon105.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/105Popkas.png", "Grass", None)
Frikitiki = Pokemon("Frikitiki", "#106", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon106.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/106Popkas.png", "Grass", "Fire")
Unymph = Pokemon("Unymph", "#107", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon107.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/107Popkas.png", "Bug", None)
Harptera = Pokemon("Harptera-A", "#108", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon108.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/108Popkas.png", "Bug", "Flying")
Chicoatl = Pokemon("Chicoatl", "#109", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon109.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/109Popkas.png", "Grass", None)
Quetzoral = Pokemon("Quetzoral", "#110", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon110.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/110Popkas.png", "Grass", "Flying")
#111-#120
Coatlith = Pokemon("Coatlith", "#111", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon111.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/111Popkas.png", "Grass", "Dragon")
Tracton = Pokemon("Tracton", "#112", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon112.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/112Popkas.png", "Dragon", "Steel")
Snopach = Pokemon("Snopach", "#113", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon113.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/113Popkas.png", "Ice", "Rock")
Dermafrost = Pokemon("Dermafrost", "#114", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon114.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/114Popkas.png", "Ice", "Rock")
Slothohm = Pokemon("Slothohm", "#115", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon115.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/115Popkas.png", "Electric", "Rock")
Theriamp = Pokemon("Theriamp", "#116", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon116.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/116Popkas.png", "Electric", "Rock")
Titanice = Pokemon("Titanice", "#117", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon117.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/117Popkas.png", "Ice", None)
Frynai = Pokemon("Frynai", "#118", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon118.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/118Popkas.png", "Water", "Steel")
Saidine = Pokemon("Saidine", "#119", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon119.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/119Popkas.png", "Water", "Steel")
Daikatuna = Pokemon("Daikatuna", "#120", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon120.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/120Popkas.png", "Water", "Steel")
#121-#130
Selkid = Pokemon("Selkid", "#121", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon121.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/121Popkas.png", "Water", "Fairy")
Mega_Syrentide = Pokemon("Mega Syrentide", "#122", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon122.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/122_1Popkas.png", "Water", "Fairy")
Syrentide = Pokemon("Syrentide", "#122", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon122.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/122Popkas.png", "Water", "Fairy", Mega_Syrentide)
Spritzee = Pokemon("Spritzee", "#123", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon123.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/123Popkas.png", "Fairy", None)
Aromatisse = Pokemon("Aromatisse", "#124", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon124.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/124Popkas.png", "Fairy", None)
Miasmedic = Pokemon("Miasmedic", "#125", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon125.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/125Popkas.png", "Fairy", "Poison")
Winotinger = Pokemon("Winotinger", "#126", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon126.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/126Popkas.png", "Fairy", "Fighting")
Titanice = Pokemon("Titanice", "#127", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon127.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/127Popkas.png", "Fairy", "Fighting")
Duplicat = Pokemon("Duplicat", "#128", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon128.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/128Popkas.png", "Normal", None)
Eevee = Pokemon("Eevee", "#129", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon129.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/129Popkas.png", "Normal", None)
Vaporeon = Pokemon("Vaporeon", "#130", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon130.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/130Popkas.png", "Water", None)
#131-#140
Jolteon = Pokemon("Jolteon", "#131", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon131.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/131Popkas.png", "Electric", None)
Flareon = Pokemon("Flareon", "#132", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon132.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/132Popkas.png", "Fire", None)
Espeon = Pokemon("Espeon", "#133", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon133.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/133Popkas.png", "Psychic", None)
Umbreon = Pokemon("Umbreon", "#134", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon134.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/134Popkas.png", "Dark", None)
Leafeon = Pokemon("Leafeon", "#135", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon135.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/135Popkas.png", "Grass", None)
Glaceon = Pokemon("Glaceon", "#136", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon136.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/136Popkas.png", "Ice", None)
Sylveon = Pokemon("Sylveon", "#137", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon137.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/137Popkas.png", "Fairy", None)
Nucleon = Pokemon("Nucleon", "#138", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon138.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/138Popkas.png", "Nuclear", None)
Ratsy = Pokemon("Ratsy", "#139", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon139.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/139Popkas.png", "Dark", None)
Raffiti = Pokemon("Raffiti", "#140", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon140.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/140Popkas.png", "Dark", None)
#141-#150
Gargryph = Pokemon("Gargryph", "#141", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon141.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/141Popkas.png", "Rock", None)
Masking = Pokemon("Masking", "#142", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon142.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/142Popkas.png", "Psychic", None)
Mega_Dramsama = Pokemon("Mega Dramsama", "#143", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon143.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/143_1Popkas.png", "Psychic", "Ghost")
Dramsama = Pokemon("Dramsama", "#143", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon143.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/143Popkas.png", "Psychic", "Ghost", Mega_Dramsama)
Antarki = Pokemon("Antarki", "#144", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon144.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/144Popkas.png", "Ghost", "Fire")
Nuclear_Chupacho = Pokemon("Nuclear Chupacho", "#145", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon145.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N145Popkas.png", "Poison", "Nuclear")
Chupacho = Pokemon("Chupacho", "#145", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon145.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/145Popkas.png", "Poison", None, Nuclear_Chupacho)
Nuclear_Luchabra = Pokemon("Nuclear Luchabra", "#146", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon146.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N146Popkas.png", "Poison", "Nuclear")
Luchabra = Pokemon("Luchabra", "#146", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon146.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/146Popkas.png", "Poison", "Fighting", Nuclear_Luchabra)
Linkite = Pokemon("Linkite", "#147", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon147.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/147Popkas.png", "Ghost", None)
Chainite = Pokemon("Chainite", "#148", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon148.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/148Popkas.png", "Ghost", "Dark")
Pufluff = Pokemon("Pufluff", "#149", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon149.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/149Popkas.png", "Ice", "Fairy")
Alpico = Pokemon("Alpico", "#150", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon150.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/150Popkas.png", "Ice", "Fairy")
#151-#160
Anderind = Pokemon("Anderind", "#151", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon151.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/151Popkas.png", "Ice", "Ground")
Colarva = Pokemon("Colarva", "#152", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon152.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/152Popkas.png", "Bug", "Ice")
Frosulo = Pokemon("Frosulo", "#153", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon153.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/153Popkas.png", "Bug", "Ice")
Frosthra = Pokemon("Frosthra", "#154", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon154.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/154Popkas.png", "Bug", "Ice")
Fafurr = Pokemon("Fafurr", "#155", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon155.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/155Popkas.png", "Ice", "Dragon")
Fafninter = Pokemon("Fafninter", "#156", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon156.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/156Popkas.png", "Ice", "Dragon")
Shrimputy = Pokemon("Shrimputy", "#157", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon157.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/157Popkas.png", "Water", "Fire")
Krilvolver = Pokemon("Krilvolver", "#158", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon158.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/158Popkas.png", "Water", "Fire")
Lavent = Pokemon("Lavent", "#159", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon159.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/159Popkas.png", "Fire", "Dragon")
Swabone = Pokemon("Swabone", "#160", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon160.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/160Popkas.png", "Ghost", "Fighting")
#161-#170
Skelerogue = Pokemon("Skelerogue", "#161", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon161.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/161Popkas.png", "Ghost", "Fighting")
Navighast = Pokemon("Navighast", "#162", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon162.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/162Popkas.png", "Ghost", "Fighting")
Stenowatt = Pokemon("Stenowatt", "#163", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon163.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/163Popkas.png", "Electric", None)
Jungore = Pokemon("Jungore", "#164", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon164.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/164Popkas.png", "Fighting", "Rock")
Majungold = Pokemon("Majungold", "#165", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon165.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/165Popkas.png", "Fighting", "Rock")
Nuclear_Hagoop = Pokemon("Nuclear Hagoop", "#166", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon166.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N166Popkas.png", "Poison", "Nuclear")
Hagoop = Pokemon("Hagoop", "#166", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon166.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/166Popkas.png", "Poison", "Electric", Nuclear_Hagoop)
Nuclear_Haagross = Pokemon("Nuclear Haagross", "#167", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon167.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/167Popkas.png", "Poison", "Nuclear")
Haagross = Pokemon("Haagross", "#167", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon167.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/167Popkas.png", "Poison", "Electric")
Xenomite = Pokemon("Xenomite", "#168", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon168.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/168Popkas.png", "Nuclear", None)
Xenogen = Pokemon("Xenogen", "#169", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon169.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/169Popkas.png", "Nuclear", None)
Xenoqueen = Pokemon("Xenoqueen", "#170", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon170.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/170Popkas.png", "Nuclear", None)
#171-#180
Hazma = Pokemon("Hazma", "#171", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon171.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/171Popkas.png", "Nuclear", None)
Geigeroach = Pokemon("Geigeroach", "#172", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon172.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/172Popkas.png", "Bug", "Nuclear")
Minicorn = Pokemon("Minicorn", "#173", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon173.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/173Popkas.png", "Fairy", "Normal")
Mega_Kiricorn = Pokemon("Mega Kiricorn", "#174", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon174.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/174_1Popkas.png", "Fairy", "Normal")
Kiricorn = Pokemon("Kiricorn", "#174", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon174.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/174Popkas.png", "Fairy", "Normal", Mega_Kiricorn)
Oblivicorn = Pokemon("Oblivicorn", "#175", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon175.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/175Popkas.png", "Fairy", "Dark")
Luxi = Pokemon("Luxi", "#176", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon176.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/176Popkas.png", "Dragon", "Fairy")
Luxor = Pokemon("Luxor", "#177", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon177.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/177Popkas.png", "Dragon", "Fairy")
Luxelong = Pokemon("Luxelong", "#178", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon178.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/178Popkas.png", "Dragon", "Fairy")
Praseopunk = Pokemon("Praseopunk", "#179", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon179.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/179Popkas.png", "Psychic", "Electric")
Neopunk = Pokemon("Neopunk", "#180", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon180.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/180Popkas.png", "Psychic", "Electric")
#181-#190
Sheebit = Pokemon("Sheebit", "#181", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon181.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/181Popkas.png", "Ground", None)
Terrabbit = Pokemon("Terrabbit", "#182", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon182.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/182Popkas.png", "Ground", None)
Laissure = Pokemon("Laissure", "#183", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon183.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/183Popkas.png", "Ground", None)
Volchik = Pokemon("Volchik", "#184", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon184.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/184Popkas.png", "Electric", "Flying")
Voltasu = Pokemon("Voltasu", "#185", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon185.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/185Popkas.png", "Electric", "Flying")
Yatagaryu = Pokemon("Yatagaryu", "#186", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon186.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/186Popkas.png", "Electric", "Dragon")
Devimp = Pokemon("Devimp", "#187", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon187.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/187Popkas.png", "Fire", "Dark")
Fallengel = Pokemon("Fallengel", "#188", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon188.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/188Popkas.png", "Fire", "Dark")
Beliaddon = Pokemon("Beliaddon", "#189", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon189.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/189Popkas.png", "Fire", "Dark")
Seikamater = Pokemon("Seikamater", "#190", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon190.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/190Popkas.png", "Bug", "Normal")
#191-#200
Garlikid = Pokemon("Garlikid", "#191", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon191.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/191Popkas.png", "Grass", "Fighting")
Baitatao = Pokemon("Baitatao", "#192", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon192.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/192Popkas.png", "Water", "Fire")
Leviathao = Pokemon("Leviathao", "#193", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon193.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/193Popkas.png", "Water", "Ice")
Krakanao = Pokemon("Krakanao", "#194", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon194.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/194Popkas.png", "Water", "Dark")
Lanthan = Pokemon("Lanthan", "#195", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon195.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/195Popkas.png", "Ground", "Steel")
Nuclear_Actan = Pokemon("Nuclear Actan", "#196", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon196.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Nuclear/N196Popkas.png", "Nuclear", "Steel")
Actan = Pokemon("Actan", "#196", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon196.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/196Popkas.png", "Dark", "Steel", Nuclear_Actan)
Gamma_Urayne = Pokemon("Gamma Urayne", "#197", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon197.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/197_2Popkas.png", "Nuclear", None)
Alpha_Urayne = Pokemon("Alpha Urayne", "#197", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon197.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Mega/197_1Popkas.png", "Nuclear", None, Gamma_Urayne)
Urayne = Pokemon("Urayne", "#197", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon197.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/197Popkas.png", "Nuclear", None, Alpha_Urayne)
Aotius = Pokemon("Aotius", "#198", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon198.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/198Popkas.png", "Flying", "Fire")
Mutios = Pokemon("Mutios", "#199", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon199.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/199Popkas.png", "Ghost", "Water")
Zephy = Pokemon("Zephy", "#200", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Sprites/Icon0200.gif", "https://raw.githubusercontent.com/infinitel8p/PokeDexSprites/main/Uranium/Pokemon/200Popkas.png", "Electric", "Ice")

Pokédex_Uranium =   [Orchynx, Mega_Metalynx, Metalynx, Raptorch, Mega_Archilles, Archilles, Eletux, Mega_Electruxo, Electruxo, Nuclear_Chyinmunk, Chyinmunk, Nuclear_Kinetmunk, Kinetmunk, Birbie, Aveden, #000-#010
                    Splendifowl, Cubbug, Cubblfly, Nimflora, Barewl, Dearewl, Gararewl, Grozard, Terlard, Nuclear_Tonemy, Tonemy, #011-#020
                    Nuclear_Tofurang, Tofurang, Dunsparce, Dunseraph, Fortog, Folerog, Blubelrog, Nuclear_Magikarp, Magikarp, Mega_Nuclear_Gyarados, Mega_Gyarados, Gyarados, Feleng, #021-#030
                    Felunge, Feliger, Mankey, Primeape, Empirilla, Nuclear_Owten, Owten, Nuclear_Eshouten, Eshouten, Lotad, Lombre, Ludicolo, Smore, #031-#040
                    Firoke, Brailip, Brainoar, Nuclear_Ekans, Ekans, Mega_Nuclear_Arbok, Mega_Arbok, Arbok, Nuclear_Tancoon, Tancoon, Nuclear_Tanscure, Tanscure, Sponee, Sponaree, Nuclear_Pahar, Pahar, #041-#050
                    Nuclear_Palij, Palij, Nuclear_Pajay, Pajay, Nuclear_Jerbolta, Jerbolta, Comite, Cometeor, Astronite, Mareep, Flaaffy, Mega_Amphoros, Ampharos, Nuclear_Baashaun, Baashaun, #051-#060
                    Nuclear_Baaschaf, Baaschaf, Mega_Nuclear_Baariette, Mega_Baariette, Baariette, Tricwe, Harylect, Nuclear_Costraw, Costraw, Nuclear_Trawpint, Trawpint, Lunapup, Herolune, Minyan, Vilucard, #061-#070
                    Buizel, Floatzel, Modrille, Mega_Drilgann, Drilgann, Nuclear_Gligar, Gligar, Nuclear_Gliscor, Gliscor, Mega_Sableye, Sableye, Cocaran, Cararalm, Cocancer, #071-#080
                    Nuclear_Corsola, Corsola, Nuclear_Corsoreef, Corsoreef, Nuclear_Tubjaw, Tubjaw, Nuclear_Tubareel, Tubareel, Cassnail, Sableau, Escartress, Nuclear_Nupin, Nupin, Nuclear_Gellin, Gellin, Cottonee, #081-#090
                    Mega_Whimsicott, Whimsicott, Misdreavus, Mismagius, Nuclear_Barand, Barand, Glaslug, Glavinug, S_fifty_one, Mega_S_fity_one_A, S_fifty_one_A, Nuclear_Paraudio, Paraudio, Nuclear_Paraboom, Paraboom, #091-#100
                    Flager, Mega_Inflagetah, Inflagetah, Chimical, Chimaconda, Tikiki, Frikitiki, Unymph, Harptera, Chicoatl, Quetzoral, #101-#110
                    Coatlith, Tracton, Snopach, Dermafrost, Slothohm, Theriamp, Titanice, Frynai, Saidine, Daikatuna, #111-#120
                    Selkid, Mega_Syrentide, Syrentide, Spritzee, Aromatisse, Miasmedic, Winotinger, Titanice, Duplicat, Eevee, Vaporeon, #121-#130
                    Jolteon, Flareon, Espeon, Umbreon, Leafeon, Glaceon, Sylveon, Nucleon, Ratsy, Raffiti, #131-#140
                    Gargryph, Masking, Mega_Dramsama, Dramsama, Antarki, Nuclear_Chupacho, Chupacho, Nuclear_Luchabra, Luchabra, Linkite, Chainite, Pufluff, Alpico, #141-#150
                    Anderind, Colarva, Frosulo, Frosthra, Fafurr, Fafninter, Shrimputy, Krilvolver, Lavent, Swabone, #151-#160
                    Skelerogue, Navighast, Stenowatt, Jungore, Majungold, Nuclear_Hagoop, Hagoop, Nuclear_Haagross, Haagross, Xenomite, Xenogen, Xenoqueen, #161-#170
                    Hazma, Geigeroach, Minicorn, Mega_Kiricorn, Kiricorn, Oblivicorn, Luxi, Luxor, Luxelong, Praseopunk, Neopunk, #171-#180
                    Sheebit, Terrabbit, Laissure, Volchik, Voltasu, Yatagaryu, Devimp, Fallengel, Beliaddon, Seikamater, #181-#190
                    Garlikid, Baitatao, Leviathao, Krakanao, Lanthan, Nuclear_Actan, Actan, Gamma_Urayne, Alpha_Urayne, Urayne, Aotius, Mutios, Zephy #191-#200
                    ]

german_type_names = {"Bug": ["Pokémon Typ: *Käfer*\n", "Doppelter Schaden: \n - Feuer \n - Flug \n - Gestein \n - Nuklear", "Halber Schaden: \n - Pflanze \n - Kampf \n - Boden", "Kein Schaden:\n", "k.A."],
                    "Dark" : ["Pokémon Typ: *Unlicht*\n", "Doppelter Schaden: \n - Kampf \n - Käfer \n - Fee \n - Nuklear", "Halber Schaden: \n - Geist \n - Unlicht", "Kein Schaden: \n - Psycho\n", "k.A."],
                    "Dragon" : ["Pokémon Typ: *Drache*\n", "Doppelter Schaden: \n - Eis \n - Drache \n - Fee \n - Nuklear", "Halber Schaden: \n - Feuer \n - Wasser \n - Pflanze \n - Elektro", "Kein Schaden:\n", "k.A."],
                    "Electric" : ["Pokémon Typ: *Elektro*\n", "Doppelter Schaden: \n - Boden \n - Nuklear", "Halber Schaden: \n - Elektro \n - Flug \n - Stahl", "Kein Schaden:\n", "Elektro-Pokémon können nicht paralysiert \nwerden."],
                    "Fairy" : ["Pokémon Typ: *Fee*\n", "Doppelter Schaden: \n - Gift \n - Nuklear", "Halber Schaden: \n - Kampf \n - Käfer \n - Unlicht", "Kein Schaden: \n - Drache\n", "k.A."],
                    "Fighting" : ["Pokémon Typ: *Kampf*\n", "Doppelter Schaden: \n - Flug \n - Psycho \n - Fee \n - Nuklear", "Halber Schaden: \n - Käfer \n - Gestein \n - Unlicht", "Kein Schaden:\n", "k.A."],
                    "Fire" : ["Pokémon Typ: *Feuer*\n", "Doppelter Schaden: \n - Wasser \n - Boden \n - Gestein \n - Nuklear", "Halber Schaden: \n - Feuer \n - Pflanze \n - Eis \n - Käfer \n - Stahl \n - Fee\n", "Kein Schaden:\n", "k.A."],
                    "Flying" : ["Pokémon Typ: *Flug*\n", "Doppelter Schaden: \n - Elektro \n - Eis \n - Gestein \n - Nuklear", "Halber Schaden: \n - Pflanze \n - Kampf \n - Käfer", "Kein Schaden: \n - Boden\n", "Flug-Pokémon erleiden keinen Schaden durch \nStachler. Außerdem können sie durch Giftspitzen \nnicht vergiftet werden und erhalten keine Senkung \nder Initiative durch das Klebenetz.\nWeiterhin können sie auch fliehen, selbst wenn das \ngegnerische Pokémon die Fähigkeit Ausweglos besitzt.\nGleiches gilt auch für Pokémon mit der Fähigkeit \nSchwebe."],
                    "Ghost" : ["Pokémon Typ: *Geist*\n", "Doppelter Schaden: \n - Geist \n - Unlicht \n - Nuklear", "Halber Schaden: \n - Gift \n - Käfer", "Kein Schaden: \n - Normal \n - Kampf\n", "Geist-Pokémon können auch fliehen, selbst wenn \ndas gegnerische Pokémon die Fähigkeit Wegsperre oder \nAusweglos besitzt.Wenn ein Geist-Pokémon den Zweit -\ntyp Stahl besitzt kann es auch fliehen,\nwenn das gegnerische Pokémon die Fähigkeit Magnetfalle \nbesitzt."],
                    "Grass" : ["Pokémon Typ: *Pflanze*\n", "Doppelter Schaden: \n - Feuer \n - Eis \n - Gift \n - Flug \n - Käfer \n - Nuklear", "Halber Schaden: \n - Wasser \n - Pflanze \n - Elektro \n - Boden", "Kein Schaden:\n", "Pflanze-Pokémon sind immun gegen Egelsamen, \nSporen -  und Puder - Attacken."],
                    "Ground" : ["Pokémon Typ: *Boden*\n", "Doppelter Schaden:  \n - Wasser \n - Pflanze \n - Eis \n - Nuklear", "Halber Schaden: \n - Gift \n - Gestein", "Kein Schaden: \n - Elektro\n", "Boden-Pokémon können nicht durch Donnerwelle \nparalysiert werden. Außerdem erleiden sie keinen \nSchaden im Sandsturm."],
                    "Ice" : ["Pokémon Typ: *Eis*\n", "Doppelter Schaden: \n - Feuer \n - Kampf \n - Gestein \n - Stahl \n - Nuklear", "Halber Schaden: \n - Eis", "Kein Schaden:\n", "Eis-Pokémon erleiden keinen Schaden im Hagel \nund können nicht eingefroren werden."],
                    "Normal" : ["Pokémon Typ: *Normal*\n", "Doppelter Schaden: \n - Kampf \n - Nuklear", "Halber Schaden:", "Kein Schaden: \n - Geist\n", "k.A."],
                    "Poison" : ["Pokémon Typ: *Gift*\n", "Doppelter Schaden: \n - Boden \n - Psycho \n - Nuklear", "Halber Schaden: \n - Pflanze \n - Kampf \n - Gift \n - Käfer \n - Fee", "Kein Schaden:\n", "Gift-Pokémon können weder vergiftet noch \nschwer vergiftet werden. Weiterhin kann jedes \nGift-Pokémon, das den Boden berührt,\nGiftspitzen sofort von der eigenen Feldseite entfernen.\nZu guter Letzt wird die Statusattacke Toxin nie ihr \nZiel verfehlen, wenn sie von einem Gift-Pokémon\neingesetzt wird."],
                    "Psychic" : ["Pokémon Typ: *Psycho*\n", "Doppelter Schaden: \n - Käfer \n - Geist \n - Unlicht \n - Nuklear", "Halber Schaden: \n - Kampf \n - Psycho", "Kein Schaden:\n", "k.A."],
                    "Rock" : ["Pokémon Typ: *Gestein*\n", "Doppelter Schaden: \n - Wasser \n - Pflanze \n - Kampf \n - Boden \n - Stahl \n - Nuklear", "Halber Schaden: \n - Normal \n - Feuer \n - Gift \n - Flug", "Kein Schaden:\n", "Gestein-Pokémon erleiden keinen Schaden\nim Sandsturm. Außerdem erhöht sich deren \nSpezial - Verteidigung um 50%, wenn ein Sandsturm\nherrscht."],
                    "Steel" : ["Pokémon Typ: *Stahl*\n", "Doppelter Schaden: \n - Feuer \n - Kampf \n - Boden", "Halber Schaden: \n - Normal \n - Pflanze \n - Eis \n - Flug \n - Psycho \n - Käfer \n - Gestein \n - Drache \n - Stahl \n - Fee \n - Nuklear", "Kein Schaden: \n - Gift\n", "Stahl-Pokémon erleiden keinen Schaden durch \nSandsturm. Weiterhin können sie durch Toxin \nund Giftspitzen nicht vergiftet werden."],
                    "Water" : ["Pokémon Typ: *Wasser*\n", "Doppelter Schaden: \n - Pflanze \n - Elektro \n - Nuklear", "Halber Schaden: \n - Feuer \n - Wasser \n - Eis \n - Stahl", "Kein Schaden:\n", "k.A."],
                    "Nuklear" : ["Pokémon Typ: *Nuklear*\n", "Doppelter Schaden: \n - Normal \n - Feuer \n - Kampf \n - Wasser \n - Flug \n - Pflanze \n - Elektro \n - Boden \n - Psycho \n - Gestein \n - Eis \n - Käfer \n - Drache \n - Geist \n - Unlicht \n - Stahl \n - Fee \n - Gift", "Halber Schaden: \n - Nuklear ", "Kein Schaden:\n", "k.A."]
                    }

english_type_names = {"Bug": ["Pokémon type: *Bug*\n", "Double damage: \n - Fire \n - Flying \n - Rock \n - Nuclear", "Half damage: \n - Grass \n - Fighting \n - Ground", "No damage: \n", "n / a"],
                    "Dark" : ["Pokémon type: *Dark*\n", "Double damage: \n - Fighting \n - Bug \n - Fairy \n - Nuclear", "Half damage: \n - Ghost \n - Dard", "No damage: \n - Psychic\n", "n / a"],
                    "Dragon" : ["Pokémon type: *Dragon*\n", "Double damage: \n - Ice \n - Dragon \n - Fairy \n - Nuclear", "Half damage: \n - Fire \n - Water \n - Grass \n - Electric", "No damage: \n", "n / a"],
                    "Electric" : ["Pokémon type: *Electric*\n", "Double damage: \n - Ground \n - Nuclear", "Half damage: \n - Electric \n - Flying \n - Steel", "No damage: \n", "Electric-type Pokémon are immune to paralysis."],
                    "Fairy" : ["Pokémon type: *Fairy*\n", "Double damage: \n - Poison \n - Nuclear", "Half damage: \n - Fighting \n - Bug \n - Dark", "No damage: \n - Dragon\n", "n / a"],
                    "Fighting" : ["Pokémon type: *Fighting*\n", "Double damage: \n - Flying \n - Psychic \n - Fairy \n - Nuclear", "Half damage: \n - Bug \n - Rock \n - Dark", "No damage: \n", "n / a"],
                    "Fire" : ["Pokémon type: *Fire*\n", "Double damage: \n - Water \n - Ground \n - Rock \n - Nuclear", "Half damage: \n - Fire \n - Grass \n - Ice \n - Bug \n - Steel \n - Fairy\n", "No damage: \n", "n / a"],
                    "Flying" : ["Pokémon type: *Flying*\n", "Double damage: \n - Electric \n - Ice \n - Rock \n - Nuclear", "Half damage: \n - Grass \n - Fighting \n - Bug", "No damage: \n - Ground\n", "In addition to being immune to Ground-type\nattacks and Arena Trap, Flying-type Pokémon are\nunaffected by Rototiller and all entry\nhazards (except Stealth Rock).\nFlying-type Pokémon also cannot absorb Toxic Spikes\nsimply by switching in and do not receive the\nbenefits from terrains.\nThese immunities are removed when a Flying-type\nPokémon is grounded by Ingrain, Gravity, Smack Down,\nThousand Arrows or Iron Ball."],
                    "Ghost" : ["Pokémon type: *Ghost*\n", "Double damage: \n - Ghost \n - Dark \n - Nuclear", "Half damage: \n - Poison \n - Bug", "No damage: \n - Normal \n - Fighting\n", "Ghost-type Pokémon are immune to being trapped\nby all trapping moves and Abilities, including the\nbinding effect of moves such as Infestation.\nGhost types are also guaranteed to run from wild\nbattles regardless of Speed."],
                    "Grass" : ["Pokémon type: *Grass*\n", "Double damage: \n - Fire \n - Ice \n - Poison \n - Flying \n - Bug \n - Nuclear", "Half damage: \n - Water \n - Grass \n - Electric \n - Ground", "No damage: \n", "Grass-type Pokémon are immune to Leech Seed,\npowder and spore moves and Effect Spore."],
                    "Ground" : ["Pokémon type: *Ground*\n", "Double damage:  \n - Water \n - Grass \n - Ice \n - Nuclear", "Half damage: \n - Poison \n - Rock", "No damage: \n - Electric\n", "Ground-type Pokémon are not damaged by\nsandstorms, and are immune to Electric attacks."],
                    "Ice" : ["Pokémon type: *Ice*\n", "Double damage: \n - Fire \n - Fighting \n - Rock \n - Steel \n - Nuclear", "Half damage: \n - Ice", "No damage: \n", "Ice-type Pokémon are immune to Sheer Cold,\ndamage from hail and freezing."],
                    "Normal" : ["Pokémon type: *Normal*\n", "Double damage: \n - Fighting \n - Nuclear", "Half damage:", "No damage: \n - Ghost\n", "n / a"],
                    "Poison" : ["Pokémon type: *Poison*\n", "Double damage: \n - Ground \n - Psychic \n - Nuclear", "Half damage: \n - Grass \n - Fighting \n - Poison \n - Bug \n - Fairy", "No damage: \n", "Poison-type Pokémon are immune to being\npoisoned (except by a Pokémon with Corrosion),\nand a grounded Poison-type Pokémon automatically\nremoves Toxic Spikes on its side when it switches in.\nWhen a Poison-type uses the move Toxic, it cannot miss,\nbypassing accuracy checks and semi-invulnerable turns\nfrom moves such as Fly and Dig."],
                    "Psychic" : ["Pokémon type: *Psychic*\n", "Double damage: \n - Bug \n - Ghost \n - Dark \n - Nuclear", "Half damage: \n - Fighting \n - Psychic", "No damage: \n", "n / a"],
                    "Rock" : ["Pokémon type: *Rock*\n", "Double damage: \n - Water \n - Grass \n - Fighting \n - Ground \n - Steel \n - Nuclear", "Half damage: \n - Normal \n - Fire \n - Poison \n - Flying", "No damage: \n", "The Special Defense of a Rock-type Pokémon is\nincreased by 50% during a sandstorm,\nin addition to being immune to the damage caused by it."],
                    "Steel" : ["Pokémon type: *Steel*\n", "Double damage: \n - Fire \n - Fighting \n - Ground", "Half damage: \n - Normal \n - Grass \n - Ice \n - Flying \n - Psychic \n - Bug \n - Rock \n - Dragon \n - Steel \n - Fairy \n - Nuclear", "No damage: \n - Poison\n", "Steel-type Pokémon cannot cannot be poisoned\n(except by Corrosion) or damaged by a sandstorm."],
                    "Water" : ["Pokémon type: *Water*\n", "Double damage: \n - Grass \n - Electric \n - Nuclear", "Half damage: \n - Fire \n - Water \n - Ice \n - Steel", "No damage: \n", "n / a"],
                    "Nuclear" : ["Pokémon type: *Nuclear*\n", "Double damage: \n - Normal \n - Fire \n - Fighting \n - Water \n - Flying \n - Grass \n - Electro \n - Ground \n - Psychic \n - Rock \n - Ice \n - Bug \n - Dragon \n - Ghost \n - Dark \n - Steel \n - Fairy \n - Poison", "Half damage: \n - Nuclear ", "No damage:\n", "k.A."]
                    }

def Uranium_Search(pokemon_search_input):
    for pokemon in Pokédex_Uranium:
        if pokemon_search_input == pokemon.get_name():
            if pokemon.get_versionen() == None:
                return pokemon, None, None
            if pokemon.get_versionen() != None:
                    if pokemon.get_versionen().get_versionen() == None:
                        return pokemon, pokemon.get_versionen(), None
                    if pokemon.get_versionen().get_versionen() != None:
                        return pokemon, pokemon.get_versionen(), pokemon.get_versionen().get_versionen()
    return None, None, None

#result, test, test1 = Uranium_Search("Gyarados")
#print(result.get_name())
#print(test)
#print(test1)